/**
 * Mockup Preview Vite Plugin
 *
 * Auto-discovers React component files in `src/components/mockups/` and
 * generates a module map (`src/.generated/mockup-components.ts`) that
 * enables lazy-loading each component by path.
 *
 * How it works:
 * 1. On build start, scans the mockups directory for `.tsx` files
 * 2. Generates a TypeScript module with dynamic `import()` entries
 * 3. In dev mode, watches for file additions/removals and regenerates
 * 4. Files/folders prefixed with `_` are excluded (convention for private helpers)
 *
 * The generated module is consumed by `App.tsx` to render components
 * at routes like `/preview/ComponentName`.
 */
import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import glob from "fast-glob";
import chokidar from "chokidar";
import type { FSWatcher } from "chokidar";
import type { Plugin } from "vite";

/** Directory containing mockup component files. */
const MOCKUPS_DIR = "src/components/mockups";

/** Path to the auto-generated module map file. */
const GENERATED_MODULE = "src/.generated/mockup-components.ts";

interface DiscoveredComponent {
  /** Key used in the module map (relative to `src/`). */
  globKey: string;
  /** Import path relative to the generated module's location. */
  importPath: string;
}

/**
 * Creates the Vite plugin instance.
 *
 * @returns A Vite plugin that manages mockup component discovery and code generation.
 */
export function mockupPreviewPlugin(): Plugin {
  let root = "";
  let currentSource = "";
  let watcher: FSWatcher | null = null;

  /** Resolve the absolute path to the mockups directory. */
  function getMockupsAbsDir(): string {
    return path.join(root, MOCKUPS_DIR);
  }

  /** Resolve the absolute path to the generated module file. */
  function getGeneratedModuleAbsPath(): string {
    return path.join(root, GENERATED_MODULE);
  }

  /** Check if a file path is a valid mockup component (.tsx inside the mockups dir). */
  function isMockupFile(absolutePath: string): boolean {
    const rel = path.relative(getMockupsAbsDir(), absolutePath);
    return (
      !rel.startsWith("..") && !path.isAbsolute(rel) && rel.endsWith(".tsx")
    );
  }

  /**
   * Check if a file should be included in the preview.
   * Files and folders starting with `_` are excluded (private helpers).
   */
  function isPreviewTarget(relativeToMockups: string): boolean {
    return relativeToMockups
      .split(path.sep)
      .every((segment) => !segment.startsWith("_"));
  }

  /** Scan the mockups directory and return all discoverable components. */
  async function discoverComponents(): Promise<Array<DiscoveredComponent>> {
    const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, {
      cwd: root,
      ignore: ["**/_*/**", "**/_*.tsx"],
    });

    return files.map((f) => ({
      globKey: "./" + f.slice("src/".length),
      importPath: path.posix.relative("src/.generated", f),
    }));
  }

  /** Generate the TypeScript source for the module map. */
  function generateSource(components: Array<DiscoveredComponent>): string {
    const entries = components
      .map(
        (c) =>
          `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`,
      )
      .join(",\n");

    return [
      "// This file is auto-generated by mockupPreviewPlugin.ts — do not edit manually.",
      "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
      "export const modules: ModuleMap = {",
      entries,
      "};",
      "",
    ].join("\n");
  }

  /** Check if a request path is related to mockup components (triggers rescan on 404). */
  function shouldAutoRescan(pathname: string): boolean {
    return (
      pathname.includes("/components/mockups/") ||
      pathname.includes("/.generated/mockup-components")
    );
  }

  // Debounce mechanism to prevent concurrent refresh operations
  let refreshInFlight = false;
  let refreshQueued = false;

  /**
   * Re-scan the mockups directory and regenerate the module map if changed.
   * Returns `true` if the generated file was updated.
   */
  async function refresh(): Promise<boolean> {
    if (refreshInFlight) {
      refreshQueued = true;
      return false;
    }

    refreshInFlight = true;
    let changed = false;

    try {
      const components = await discoverComponents();
      const newSource = generateSource(components);

      if (newSource !== currentSource) {
        currentSource = newSource;
        const generatedModuleAbsPath = getGeneratedModuleAbsPath();
        mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
        writeFileSync(generatedModuleAbsPath, currentSource);
        changed = true;
      }
    } finally {
      refreshInFlight = false;
    }

    // Process any queued refresh that arrived while we were busy
    if (refreshQueued) {
      refreshQueued = false;
      const followUp = await refresh();
      return changed || followUp;
    }

    return changed;
  }

  /** Handler for file add/remove events in the mockups directory. */
  async function onFileAddedOrRemoved(): Promise<void> {
    await refresh();
  }

  /* -------------------------------------------------------------------------- */
  /*  Vite Plugin Interface                                                      */
  /* -------------------------------------------------------------------------- */

  return {
    name: "mockup-preview",
    enforce: "pre",

    configResolved(config) {
      root = config.root;
    },

    /** Generate the module map before the build starts. */
    async buildStart() {
      await refresh();
    },

    /** In dev mode, set up a file watcher to regenerate on changes. */
    async configureServer(viteServer) {
      await refresh();

      const mockupsAbsDir = getMockupsAbsDir();
      mkdirSync(mockupsAbsDir, { recursive: true });

      // Watch for new/removed mockup files
      watcher = chokidar.watch(mockupsAbsDir, {
        ignoreInitial: true,
        awaitWriteFinish: {
          stabilityThreshold: 100,
          pollInterval: 50,
        },
      });

      watcher.on("add", (file) => {
        if (
          isMockupFile(file) &&
          isPreviewTarget(path.relative(mockupsAbsDir, file))
        ) {
          void onFileAddedOrRemoved();
        }
      });

      watcher.on("unlink", (file) => {
        if (isMockupFile(file)) {
          void onFileAddedOrRemoved();
        }
      });

      // Auto-rescan on 404 responses for mockup-related paths
      // (handles the case where a new component is created while the server is running)
      viteServer.middlewares.use((req, res, next) => {
        const requestUrl = new URL(req.url ?? "/", "http://127.0.0.1");
        const pathname = requestUrl.pathname;
        const originalEnd = res.end.bind(res);

        res.end = ((...args: Parameters<typeof originalEnd>) => {
          if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
            void refresh();
          }
          return originalEnd(...args);
        }) as typeof res.end;

        next();
      });
    },

    /** Clean up the file watcher when the server shuts down. */
    async closeWatcher() {
      if (watcher) {
        await watcher.close();
      }
    },
  };
}
